# Generated by Django 3.0.8 on 2020-09-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_posts_song_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='song_name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
